### ISSUE TITLE
[FEATURE]Clone this template into HTML (template11)

### ISSUE THREAD

**Issue by dhairyaj** [Documentive/TemplateBuddy-Old#34]
**Describe the solution you'd like**
Given below is the link to the template. Download it and create the html format.
Click [here](https://drive.google.com/file/d/1GhphGV1g5hs7XiOp9KMcMkZSV_gLS9J8/view?usp=sharing) to download the file.

There would be a file format.txt in static/resume_templates/format. This file would contain all the placeholders that are to be put exactly in your clone.

<strong>Note:</strong> You can only start working on the feature if a maintainer approves that request in the discussion and the maintainer assigns it to you. **Your PR will be merged only if you are assigned to this issue.** This issue would be assigned only to a single user.

**Comment by NirmalKumarJoshi** [comment]
Hey @dhairyaj . I would like to work on it after it is allowed. Please assign this to me.

**Comment by dhairyaj** [comment]
Sure, @NirmalKumarJoshi  . It would be assigned to you. Thanks for showing interest and remember to star this, to keep updated with the activities going on in this repository.

**Comment by NirmalKumarJoshi** [comment]
@dhairyaj From when can I start working on it?

**Comment by dhairyaj** [comment]
Whenever you want to @NirmalKumarJoshi

**Comment by NirmalKumarJoshi** [comment]
Okay thanks. @dhairyaj . 
But one concern, I am not able to setup the project as the requirements.txt is still ot present. Can you please guide me to setup the same!

**Comment by frankhart2018** [comment]
Hey @NirmalKumarJoshi, you can start cloning. I will be adding the requirements file soon. You don't have to run TB webapp in order to create the template clone.

**Comment by NirmalKumarJoshi** [comment]
Okay. Will I be able to see the changes if the backend is not setup?

**Comment by frankhart2018** [comment]
Changes as in?

**Comment by NirmalKumarJoshi** [comment]
The HTML changes after I create the clone.

**Comment by frankhart2018** [comment]
But how does that relate to the backend? You clone the template with the placeholders and then submit it for review. That will then be used by other people. But during creation of the template's HTML you can see what you are making right from your browser right?

**Comment by NirmalKumarJoshi** [comment]
Okay thanks. Will do that :)

**Comment by frankhart2018** [comment]
Great. Hope I could help you.

**Comment by frankhart2018** [comment]
Also I have pushed requirements.txt, if you want you can check that out too.

**Comment by NirmalKumarJoshi** [comment]
Awesome. Thanks @frankhart2018 . Now i will try to do the complete setup.

**Comment by frankhart2018** [comment]
Sure

**Comment by NirmalKumarJoshi** [comment]
Hey I am getting this error here and same in the browser as well. 
![Screenshot from 2020-09-25 20-04-31](https://user-images.githubusercontent.com/29129357/94279974-7dc68580-ff6a-11ea-8b53-b4c6dce3e6fc.png)

**Comment by frankhart2018** [comment]
Fixed this, pull now. Thanks for reporting this bug.

**Comment by NirmalKumarJoshi** [comment]
Getting the same again. I guess there is a 'f' alphabet which is creating issue. Should I make the fix?

**Comment by frankhart2018** [comment]
Can you share the screenshot?

**Comment by NirmalKumarJoshi** [comment]
![error](https://user-images.githubusercontent.com/29129357/94332575-0f2e0a00-fff4-11ea-8bdb-8c7a9b19846e.png)
This comes when I run the localhost. I have pulled the recent code as well but still getting this.

**Comment by frankhart2018** [comment]
Hey @NirmalKumarJoshi can you send the following details:-

1) OS name and version
2) Python version
3) The command you are using to start the server

Because I tested in windows, macOS and linux and everywhere it is working fine.

**Comment by dhairyaj** [comment]
@NirmalKumarJoshi , though it's great that you are finding some bugs in the project but its still a bit incomplete on the backend part and our developers are working on it. So, some things might be broken. Rest assured, you donot need to setup the project in your system in order to create the template clone that was assigned to you. So you can get working on it. Thanks

**Comment by devtechnocode** [comment]
Hello @dhairyaj, I would like to work on this issue. Please assign this to me.

**Comment by ineffable23** [comment]
@dhairyaj I'm highly interested to work on this issue please assign it to me.

**Comment by dhairyaj** [comment]
Assigning to @devtechnocode

**Comment by dhairyaj** [comment]
@ineffable23 , @devtechnocode asked for it first. You can pick any other issue as well. If you don't find any other issue of  your interest, we would be adding some more issue by today evening. Thanks
